---
title: "plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Plotly

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r}
data("nyc_airbnb")

nyc_airbnb <-
  nyc_airbnb %>%
  mutate(stars = review_scores_location/2) %>%
  select(borough = neighbourhood_group,
         neighbourhood, stars, price, room_type, lat, long) %>%
  drop_na(stars) %>%
  filter(borough == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)
```

Let's make a scatterplot!

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating:", stars)) %>%
  plot_ly(x = ~lat, y = ~long, color = ~price, text = ~text_label,
          type = "scatter", mode = "markers", alpha = .5)
```


Let's make a boxplot!

```{r}
nyc_airbnb %>%
  plot_ly(y = ~price, color = ~neighbourhood, type = "box")
```


Let's make a barplot!

```{r}
nyc_airbnb %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(
    x = ~neighbourhood, color = 
  )
```




